export type ServiceArea = {
  slug: string
  city: string
  state: string
  county: string
  intro: string
  rooferSection: string
  neighborhoods: string
}

export const serviceAreas: ServiceArea[] = [
  {
    slug: 'alvarado-tx',
    city: 'Alvarado',
    state: 'TX',
    county: 'Johnson County',
    intro: 'At Kingdom Care Roofing and Construction LLC, we understand what makes Alvarado unique and take pride in serving this community by providing protection for its homes and businesses.',
    rooferSection: 'Our roofing solutions are built around what Alvarado residents actually need. We work with the Texas climate and local architecture in mind, covering everything from metal and shingle roofing to emergency repairs and storm damage restoration.',
    neighborhoods: '',
  },
  {
    slug: 'arlington-tx',
    city: 'Arlington',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'Arlington, TX, is a vibrant city known for its significant role in North Texas culture. Home to the Cowboys Stadium and Six Flags Over Texas, it offers a blend of excitement and tradition. In Arlington, you\'ll find a tight-knit community bustling with energy and enthusiasm, and we at Kingdom Care Roofing and Construction LLC are proud to call this place our service area.',
    rooferSection: 'At Kingdom Care Roofing, we are glad to serve Arlington residents. We offer services built around local needs, keeping your home safe and structurally sound. That includes shingle and tile roofing, storm damage restoration, and exterior painting.',
    neighborhoods: 'Wherever you are in Arlington, our experienced team stands ready to provide the best roofing solutions. Reach out to us today to schedule a free, no-obligation inspection. Let Kingdom Care Roofing and Construction LLC be your trusted partner in keeping your home safe and sound.',
  },
  {
    slug: 'benbrook-tx',
    city: 'Benbrook',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'Nestled in the dynamic heart of Texas, Benbrook offers residents both the tranquility of nature and the excitement of city life nearby. It is known for its lovely parks and welcoming neighborhood vibe, making it a beloved place for families and individuals alike.',
    rooferSection: 'At Kingdom Care Roofing and Construction LLC, we\'re dedicated to providing tailored roofing solutions for Benbrook homeowners. Whether it\'s a full replacement or minor repairs after a storm, our team delivers exceptional quality backed by our workmanship warranty.',
    neighborhoods: '',
  },
  {
    slug: 'briaroaks-tx',
    city: 'Briaroaks',
    state: 'TX',
    county: 'Johnson County',
    intro: 'Briaroaks is a charming corner of Texas known for its strong sense of community and picturesque residential areas. It offers a peaceful lifestyle close to nature while still being within easy reach of the big city amenities available in the broader Dallas-Fort Worth area.',
    rooferSection: 'Whether you\'re a long-time homeowner or new to this scenic community, Kingdom Care Roofing and Construction LLC is here to keep your home protected. We provide expert roofing, painting, and exterior construction services to Briaroaks residents with the care and integrity this community deserves.',
    neighborhoods: '',
  },
  {
    slug: 'burleson-tx',
    city: 'Burleson',
    state: 'TX',
    county: 'Johnson & Tarrant County',
    intro: 'Burleson, TX, is more than just a vibrant city with friendly faces. Known for its wonderful community spirit and thriving local businesses, Burleson is a place where neighbors become friends. It\'s rich in parks and offers a great quality of life for families, making it a cherished place to call home.',
    rooferSection: 'Kingdom Care Roofing and Construction LLC is based right here in Burleson. We know Texas weather, and we build roofs that hold up to it. Every project gets our full attention, backed by our warranty and years of local experience.',
    neighborhoods: 'Wherever you are in Burleson, we\'ve got your roofing needs covered. From the budding families in Oak Valley to the bustling businesses in Town Center, our team is ready to serve you.',
  },
  {
    slug: 'cedar-hill-tx',
    city: 'Cedar Hill',
    state: 'TX',
    county: 'Dallas & Ellis County',
    intro: 'Cedar Hill boasts a perfect blend of scenic parks and modern amenities. Cedar Hill State Park is a favorite among locals, offering lakeside beauty and outdoor adventure. The city celebrates its rich history and tradition while thriving with a forward-moving spirit.',
    rooferSection: 'At Kingdom Care Roofing and Construction LLC, we are the go-to experts for all your roofing and exterior construction needs in Cedar Hill. We\'re committed to delivering quality solutions that protect your home for decades to come, from shingle and metal roofing to storm damage restoration.',
    neighborhoods: '',
  },
  {
    slug: 'cleburne-tx',
    city: 'Cleburne',
    state: 'TX',
    county: 'Johnson County',
    intro: 'Cleburne is a vibrant city known for its rich history and southern charm. The scenic parks and historic sites like the Layland Museum reflect the town\'s wonderful heritage. We are proud to be part of such a warm and inviting community.',
    rooferSection: 'At Kingdom Care Roofing and Construction LLC, we take pride in being a family-owned business serving the Cleburne, TX community with honesty and dedication. With over 150 years of combined experience, our team knows Cleburne\'s unique weather challenges and roofing needs inside and out.',
    neighborhoods: '',
  },
  {
    slug: 'covington-tx',
    city: 'Covington',
    state: 'TX',
    county: 'Hill County',
    intro: 'Nestled in the heart of Texas, Covington is a place where neighbors know each other and help each other out. It\'s this small-town charm combined with big passion that makes Covington special.',
    rooferSection: 'With over 19 years of hands-on experience, our family-owned company values your trust and treats every project as though it\'s for our own family. We bring extensive experience and an eye for quality, ensuring that your home remains protected against Texas weather. Our commitment to customer satisfaction and community involvement makes us stand out in Covington.',
    neighborhoods: 'No matter where you live in Covington, TX, you are within our reach. Our team is ready to cater to every neighborhood, ensuring timely and efficient services. Whether you need an emergency repair or regular maintenance, we are just a call away.',
  },
  {
    slug: 'crowley-tx',
    city: 'Crowley',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'Known for its welcoming neighborhoods and community spirit, Crowley residents appreciate quality service providers who value trust and integrity. That\'s precisely why Kingdom Care Roofing and Construction LLC is dedicated to providing unbeatable service for this cherished town.',
    rooferSection: 'With 19+ years of experience, we understand exactly what Crowley homeowners need. Our professionalism and efficiency have made us a trusted name in the area. As a family-owned business, we view each customer as part of our family. Rely on us for transparent services that put your needs first.',
    neighborhoods: 'Wherever you\'re located in Crowley, rest assured that Kingdom Care Roofing and Construction LLC has got you covered. From the historic main street to the new developments, we are here to serve every corner of Crowley.',
  },
  {
    slug: 'dalworthington-gardens-tx',
    city: 'Dalworthington Gardens',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'Choosing Kingdom Care Roofing and Construction LLC means working with a family-owned business that treats every customer like a neighbor. We are available 24/7 for emergencies, and our team brings over 150 years of combined experience to every job in Dalworthington Gardens.',
    rooferSection: 'We offer a full range of services including shingle and metal roofing, complete roof installation, chimney flashing repair, emergency roof repair, roof inspections, storm damage repair, interior and exterior painting, and gutter installation and repair. All backed by our workmanship warranty.',
    neighborhoods: '',
  },
  {
    slug: 'desoto-tx',
    city: 'DeSoto',
    state: 'TX',
    county: 'Dallas County',
    intro: 'Located just a short drive away from the hustle and bustle of Dallas, DeSoto offers a more relaxed pace of life while still providing all the amenities you\'d expect from a modern city. Its friendly neighborhoods and community events reflect the spirit of Texas-sized hospitality.',
    rooferSection: 'At Kingdom Care Roofing and Construction LLC, we are proud to serve DeSoto homeowners. Our local knowledge means faster response times and work built for North Texas weather, covering everything from leak detection to full roof replacements.',
    neighborhoods: '',
  },
  {
    slug: 'duncanville-tx',
    city: 'Duncanville',
    state: 'TX',
    county: 'Dallas County',
    intro: 'Duncanville, TX, is a vibrant city known for its warm community spirit and beautiful neighborhoods. Whether you\'re enjoying a day at Alexander Park or exploring the hidden gem of Lakeside Park, Duncanville offers a slice of Texan charm that\'s hard to resist. This thriving city boasts a rich history, strong community ties, and a dedication to growth and improvement.',
    rooferSection: 'Kingdom Care Roofing and Construction LLC is proud to serve Duncanville. We use our local knowledge and hands-on experience to deliver roofing that holds up to Texas weather, from impact-resistant shingles to storm damage restoration.',
    neighborhoods: '',
  },
  {
    slug: 'edgecliff-village-tx',
    city: 'Edgecliff Village',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'Kingdom Care Roofing and Construction LLC shares these same values as the Edgecliff Village community, serving residents with genuine care and commitment. Edgecliff Village is a small, tight-knit city in Tarrant County where homeowners take great pride in their properties.',
    rooferSection: 'Our team brings over 19 years of industry experience and a combined 150 years in the field. We are here to protect your home, and we back every job with a 2-year workmanship warranty plus manufacturer coverage so you can have peace of mind.',
    neighborhoods: '',
  },
  {
    slug: 'everman-tx',
    city: 'Everman',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'Located in the thriving state of Texas, Everman is a community known for its friendly neighborhoods and rich Texan heritage. It\'s a place where families and businesses grow, marked by its warm hospitality and tight-knit community feel. Walking through Everman, you\'ll encounter a blend of charming homes and local businesses, making it a wonderful place to live, work, and play.',
    rooferSection: 'Kingdom Care Roofing and Construction LLC is proud to serve Everman. We offer free estimates, thorough inspections, and insurance claim assistance to help homeowners recover from storm damage. Every job is backed by our workmanship warranty.',
    neighborhoods: '',
  },
  {
    slug: 'forest-hill-tx',
    city: 'Forest Hill',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'Known for its welcoming neighborhoods and community parks, Forest Hill is a place where residents take pride in their homes and surroundings. At Kingdom Care Roofing and Construction LLC, we share this pride, and we\'re here to ensure your home stands out.',
    rooferSection: 'Our team at Kingdom Care Roofing and Construction LLC is here to serve Forest Hill homeowners with honest, quality work. We bring experienced craftsmanship to every job, from routine inspections to full roof replacements.',
    neighborhoods: '',
  },
  {
    slug: 'godley-tx',
    city: 'Godley',
    state: 'TX',
    county: 'Johnson County',
    intro: 'Living in Godley, TX means embracing small-town charm blended with the beautiful Texas landscape. We know residents here appreciate quality and dependability, which is exactly what we offer at Kingdom Care Roofing and Construction LLC. As a family-owned business, we treat your home like it\'s our own.',
    rooferSection: 'Let us take the worry out of roof repairs and installations, ensuring that both you and your home are well taken care of. From storm damage assessments to complete roof replacements, our experienced crew handles every detail so you don\'t have to.',
    neighborhoods: '',
  },
  {
    slug: 'grand-prairie-tx',
    city: 'Grand Prairie',
    state: 'TX',
    county: 'Dallas, Tarrant & Ellis County',
    intro: 'Known for its beautiful parks, thrilling outdoor adventures at Joe Pool Lake, and engaging community events, Grand Prairie is a city that blends the warmth of small-town living with the excitement of a bustling economy.',
    rooferSection: 'At Kingdom Care Roofing and Construction LLC, we\'re proud to be a part of this thriving community, providing services that protect and enhance the homes and buildings that make Grand Prairie unique. From storm damage repairs to full replacements, we\'ve got you covered.',
    neighborhoods: '',
  },
  {
    slug: 'joshua-tx',
    city: 'Joshua',
    state: 'TX',
    county: 'Johnson County',
    intro: 'Joshua, TX is a close-knit community known for its friendly neighborhoods and beautiful Semper Ridge Park. Families here enjoy a safe, welcoming environment and appreciate contractors who bring that same care and honesty to their work.',
    rooferSection: 'Our family-owned business has deep roots in the community and offers 24/7 services. We treat every customer like family and bring over 150 years of combined experience to every project. We are fully licensed and insured.',
    neighborhoods: 'From Cleburne to McKinney and every corner of Joshua, we provide services built around local needs. We offer free inspections and are ready to help protect your home.',
  },
  {
    slug: 'keene-tx',
    city: 'Keene',
    state: 'TX',
    county: 'Johnson County',
    intro: 'As a family-owned and insured business, Kingdom Care Roofing and Construction LLC understands what it means to do things right in a tight-knit community like Keene. Our team brings deep local knowledge and a track record of quality that Keene residents can count on.',
    rooferSection: 'We build our roofing solutions around what our Keene neighbors actually need. Whether you need a simple repair or a full roof replacement, we have options ranging from metal roofing and TPO to emergency 24/7 repair and hail damage restoration.',
    neighborhoods: '',
  },
  {
    slug: 'kennedale-tx',
    city: 'Kennedale',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'We know that trusting a contractor with your home is a big decision. As a family-owned business in Kennedale, we operate with full transparency and are completely insured. You will know what to expect from the first call to the final inspection.',
    rooferSection: 'At Kingdom Care Roofing and Construction LLC, we offer solid services built around what Kennedale homes and businesses need. That includes roof installations, shingle and metal roofing, leak detection and repairs, gutter services, and fast storm damage response.',
    neighborhoods: '',
  },
  {
    slug: 'lake-worth-tx',
    city: 'Lake Worth',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'Choosing Kingdom Care Roofing and Construction LLC means working with a team that brings over 150 years of combined experience. We are a family-owned business, and in a close-knit community like Lake Worth, we treat every customer like a neighbor.',
    rooferSection: 'We offer a full range of roofing services built for Lake Worth homeowners, including expert roof installation, leak detection and repair, metal roofing, emergency repairs, gutter installation, and storm damage restoration.',
    neighborhoods: '',
  },
  {
    slug: 'lillian-tx',
    city: 'Lillian',
    state: 'TX',
    county: 'Johnson County',
    intro: 'Kingdom Care Roofing and Construction LLC takes great pride in being a part of the wonderful Lillian community, providing reliable and professional roofing solutions tailored for every homeowner and business in the area.',
    rooferSection: 'Our seasoned team is prepared to tackle all of your needs with expertise and dedication, making us a trusted choice in Lillian. Understanding the specific requirements of our community is central to what we do. We\'ve earned a reputation for outstanding service, reflected in our customer reviews and glowing testimonials.',
    neighborhoods: 'We proudly serve every corner of Lillian, TX. Regardless of where you reside within Lillian, our experienced team is eager and ready to assist with your roofing, painting, and construction needs.',
  },
  {
    slug: 'mansfield-tx',
    city: 'Mansfield',
    state: 'TX',
    county: 'Tarrant, Johnson & Ellis County',
    intro: 'Known for its friendly neighbors and spirit of growth, Mansfield is a place where tradition and progress walk hand in hand. Among the beautiful parks and active community life, we are proud to be your local contractors, here to protect and improve the homes that make Mansfield what it is.',
    rooferSection: 'Our expert team is equipped to handle all requirements with professionalism and efficiency, making us a trusted name in Mansfield. We bring over 150 years of combined experience to every project. Whether it\'s a roof repair or a fresh installation, Kingdom Care Roofing and Construction LLC stands by your side.',
    neighborhoods: 'We are proud to serve all areas of Mansfield, TX, including Walnut Creek, Country Club, and Historic Downtown. No matter where you are in Mansfield, our team is ready to help you get a solid roof over your head.',
  },
  {
    slug: 'maypearl-tx',
    city: 'Maypearl',
    state: 'TX',
    county: 'Ellis County',
    intro: 'Known for its sense of community and scenic landscapes, Maypearl is a wonderful place to call home. It boasts a rich local history and provides a delightful retreat from the hustle and bustle of bigger cities.',
    rooferSection: 'At Kingdom Care Roofing and Construction LLC, we are committed to keeping the standard of homes in Maypearl high. From residential roof installations to full exterior painting, our team delivers quality you can see, all backed by our workmanship warranty.',
    neighborhoods: '',
  },
  {
    slug: 'midlothian-tx',
    city: 'Midlothian',
    state: 'TX',
    county: 'Ellis County',
    intro: 'Nestled perfectly between the major metropolitan areas of Dallas and Fort Worth, Midlothian is a city on the rise with a growing number of families and businesses alike choosing to call it home.',
    rooferSection: 'At Kingdom Care Roofing and Construction LLC, we understand the specific roofing needs of Midlothian homes and businesses. We offer a wide range of services, from impact-resistant shingles to TPO flat roofing, all backed by our quality guarantee.',
    neighborhoods: '',
  },
  {
    slug: 'pantego-tx',
    city: 'Pantego',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'Pantego is more than just a city; it\'s a charming community known for its friendly neighborhoods, beautiful parks, and a strong sense of local pride. With a small-town feel yet close proximity to the bustling city life of Arlington, Pantego offers the best of both worlds.',
    rooferSection: 'At Kingdom Care Roofing and Construction LLC, we build our roofing solutions around what Pantego homeowners actually need. With over 19 years of hands-on experience, we cover everything from shingle and metal roofing to storm damage restoration and gutter installation.',
    neighborhoods: '',
  },
  {
    slug: 'rendon-tx',
    city: 'Rendon',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'Nestled in Tarrant County, Rendon, TX is a hidden gem known for its spacious open landscapes and friendly neighborhoods. With a close-knit community vibe, Rendon offers a peaceful rural feel while still being conveniently close to big-city amenities. The charm of Rendon lies in its friendly residents, local parks, and unique Southern hospitality.',
    rooferSection: 'Kingdom Care Roofing and Construction LLC is proud to serve Rendon homeowners with roofing, storm damage restoration, and exterior painting. We bring the same quality and care to every project no matter the size, and we back it all with our workmanship warranty.',
    neighborhoods: '',
  },
  {
    slug: 'venus-tx',
    city: 'Venus',
    state: 'TX',
    county: 'Johnson County',
    intro: 'Nestled in the heart of Johnson County, Venus embodies the perfect blend of rural beauty and friendly residents. It\'s a place where neighbors know each other and there\'s always a helping hand nearby.',
    rooferSection: 'At Kingdom Care Roofing and Construction LLC, we offer comprehensive roofing solutions to meet the diverse needs of Venus homeowners. Whether you need a quick repair or a complete roof replacement, our experienced crew is here to help with honest pricing and quality craftsmanship.',
    neighborhoods: '',
  },
  {
    slug: 'waxahachie-tx',
    city: 'Waxahachie',
    state: 'TX',
    county: 'Ellis County',
    intro: 'Known for its beautiful historic architecture and vibrant downtown, Waxahachie is a city where neighbors still stop by to chat, and community spirit shines brightly. At Kingdom Care Roofing and Construction LLC, we are honored to serve such a friendly and welcoming community.',
    rooferSection: 'Our work in Waxahachie goes beyond roofing. We offer a full range of services to protect and improve your property, including storm damage restoration, exterior painting, and gutter installation, all backed by our quality guarantee.',
    neighborhoods: '',
  },
  {
    slug: 'white-settlement-tx',
    city: 'White Settlement',
    state: 'TX',
    county: 'Tarrant County',
    intro: 'Known for its friendly atmosphere and rich history, White Settlement is a place where traditions run deep, and neighbors become friends. As a local, family-owned business, we value the close-knit feel of White Settlement and are proud to be part of this vibrant community.',
    rooferSection: 'At Kingdom Care Roofing and Construction LLC, we offer a full range of roofing services for White Settlement homeowners. From routine maintenance to complete storm restoration, we handle every job with care, backed by our workmanship warranty.',
    neighborhoods: '',
  },
]

export function getServiceArea(slug: string): ServiceArea | undefined {
  return serviceAreas.find((a) => a.slug === slug)
}

const BASE_URL = 'https://kingdomcareroofingandconstruction.com'

const SERVICE_OFFERS = [
  'Roof Replacement',
  'Storm Damage Repair',
  'Roof Inspection',
  'Exterior Painting',
  'Gutter Installation',
  'Leak Detection & Repair',
].map((name) => ({
  '@type': 'Offer',
  itemOffered: { '@type': 'Service', name },
}))

export function generateServiceAreaSchema(area: ServiceArea) {
  const localBusiness = {
    '@context': 'https://schema.org',
    '@type': ['RoofingContractor', 'HomeAndConstructionBusiness'],
    '@id': `${BASE_URL}/#business`,
    name: 'Kingdom Care Roofing and Construction LLC',
    url: BASE_URL,
    telephone: '+1-817-888-8282',
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Burleson',
      addressRegion: 'TX',
      addressCountry: 'US',
    },
    areaServed: {
      '@type': 'City',
      name: area.city,
      containedInPlace: {
        '@type': 'AdministrativeArea',
        name: area.county,
      },
    },
    description: area.intro,
    hasOfferCatalog: {
      '@type': 'OfferCatalog',
      name: `Roofing & Construction Services in ${area.city}`,
      itemListElement: SERVICE_OFFERS,
    },
  }

  const breadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: BASE_URL },
      { '@type': 'ListItem', position: 2, name: 'Service Areas', item: `${BASE_URL}/service-areas` },
      { '@type': 'ListItem', position: 3, name: `${area.city}, ${area.state}`, item: `${BASE_URL}/service-areas/${area.slug}` },
    ],
  }

  return [localBusiness, breadcrumb]
}
